name: MSVC Conan

# This workflow is triggered on pushes to the repository.
on: [push]

env:
  SINTEF_REFERENCE: "mathgl*"
  SINTEF_LIBNAME: "mathgl"
  CONAN_UPLOAD: ${{ secrets.CONAN_URL }}
  CONAN_PASSWORD_SINTEF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.CONAN_USER }}
  CONAN_NON_INTERACTIVE: True
  CONAN_USE_ALWAYS_SHORT_PATHS: True

jobs:
  conan-with-msvc:
    name: Conan
    runs-on: ${{ matrix.os }}
    env:
      CONAN_USER_HOME_SHORT: C:\c
      CONAN_USE_ALWAYS_SHORT_PATHS: 1
    strategy:
      fail-fast: false
      matrix:
        compiler_toolset: [v141, v142, v143]
        build_type: [Debug, Release]
        option_shared: [shared=True, shared=False]
        option_qt5: [qt5=False]
        compiler_version: [17]
        os: [windows-2022]
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          pip3 install --upgrade setuptools pip
          pip3 install conan requests
          vcpkg install opengl:x64-windows
      - name: Configure Conan
        run: |
          conan remote add sintef ${env:CONAN_UPLOAD} --insert 0
          conan remote add bincrafters https://bincrafters.jfrog.io/artifactory/api/conan/public-conan --insert 0
          conan config set general.revisions_enabled=1
      - name: Conan create
        run: |
          conan create -s build_type=${{ matrix.build_type }} `
            -s compiler.version=${{ matrix.compiler_version }} `
            -s compiler.toolset=${{ matrix.compiler_toolset }} `
            -s compiler="Visual Studio" `
            -s compiler.cppstd=14 `
            -o ${env:SINTEF_LIBNAME}:${{ matrix.option_shared }} `
            -o ${env:SINTEF_LIBNAME}:${{ matrix.option_qt5 }} `
            -b missing -b outdated . sintef/steady
      - name: Conan upload
        run: |
          conan upload --all -c -r sintef ${env:SINTEF_REFERENCE} --retry 10 --retry-wait 20 --force
