name: Clang Conan

# This workflow is triggered on pushes to the repository.
on: [push]

env:
  SINTEF_REFERENCE: "mathgl*"
  SINTEF_LIBNAME: "mathgl"
  CONAN_UPLOAD: ${{ secrets.CONAN_URL }}
  CONAN_PASSWORD_SINTEF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.CONAN_USER }}
  CONAN_NON_INTERACTIVE: True
  CONAN_USE_ALWAYS_SHORT_PATHS: True
  CONAN_SYSREQUIRES_MODE: enabled

jobs:
  conan-with-clang:
    name: Conan
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        compiler_version: [9, 10]
        build_type: [Debug, Release]
        option_shared: [shared=True, shared=False]
        option_qt5: [qt5=False]
        os: [ubuntu-20.04]
        exclude:
          - option_qt5: qt5=True
            compiler_version: 9
    container:
      image: conanio/clang${{ matrix.compiler_version }}
      options: -u 0
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo pip3 install --upgrade setuptools pip
          sudo pip3 install conan requests
          sudo apt-get install nasm
      - name: Configure Conan
        run: |
          conan remote add sintef ${CONAN_UPLOAD} --insert 0
          conan remote add bincrafters https://bincrafters.jfrog.io/artifactory/api/conan/public-conan --insert 0
          conan config set general.revisions_enabled=1
      - name: Conan create
        run: |
          conan create -s build_type=${{ matrix.build_type }} \
            -s compiler.version=${{ matrix.compiler_version }} \
            -s compiler.libcxx=libstdc++11 \
            -o ${SINTEF_LIBNAME}:${{ matrix.option_shared }} \
            -o ${SINTEF_LIBNAME}:${{ matrix.option_qt5 }} \
            -b missing -b outdated . sintef/steady
      - name: Conan upload
        run: |
          conan upload --all -c -r sintef ${SINTEF_REFERENCE} --retry 5 --retry-wait 20 --force
